# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [3]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7,7)
print(tensor1)

tensor([[0.3923, 0.4803, 0.9709, 0.4282, 0.4654, 0.4871, 0.3922],
        [0.3676, 0.3539, 0.3871, 0.8803, 0.6091, 0.9626, 0.8511],
        [0.7484, 0.8120, 0.2739, 0.0546, 0.9928, 0.7495, 0.3023],
        [0.1104, 0.0249, 0.1956, 0.0064, 0.5578, 0.2226, 0.8620],
        [0.8582, 0.7322, 0.2975, 0.9729, 0.2512, 0.6880, 0.9148],
        [0.8529, 0.9403, 0.9436, 0.8150, 0.6997, 0.4360, 0.6361],
        [0.8131, 0.7391, 0.8816, 0.5815, 0.3092, 0.6450, 0.0184]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor2 = torch.rand(1,7)
# Perform matrix multiplication
tensor2_t = tensor2.t()
result = tensor1@tensor2_t
print(result)

tensor([[1.4479],
        [1.7172],
        [1.6799],
        [0.6353],
        [1.6733],
        [1.8450],
        [1.7366]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor3 = torch.rand(7,7)
tensor4 = torch.rand(7,1)
# Matrix multiply tensors
result2 = tensor3@tensor4
print(result2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)
# Create two random tensors on GPU
tensor5 = torch.rand(2, 3, device=device)
tensor6 = torch.rand(2, 3, device=device)
print((tensor5, tensor6))

Device: cuda
(tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0'), tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
result3 = torch.matmul(tensor5, tensor6.T)
print((result3, result3.shape))

(tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0'), torch.Size([2, 2]))


### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max_val = torch.max(result3)
print("max_value:" , max_val)
# Find min
min_val = torch.min(result3)
print("min_value:" , min_val)

max_value: tensor(0.7668, device='cuda:0')
min_value: tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
max_ind = torch.argmax(result3)
print("max_index:" , max_ind)
# Find arg min
min_ind = torch.argmin(result3)
print("min_index:" , min_ind)

max_index: tensor(1, device='cuda:0')
min_index: tensor(0, device='cuda:0')


**bold text**
### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor7 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor7_squeezed = tensor7.squeeze()

# Print out tensors and their shapes
print(tensor7, tensor7.shape)
print(tensor7_squeezed, tensor7_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
